//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_users
    {
        public string app_user_id { get; set; }
        public string app_id { get; set; }
        public string user_id { get; set; }
        public string datetime { get; set; }
    
        public virtual application application { get; set; }
        public virtual user user { get; set; }
    }
}
