//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public string error_id { get; set; }
        public string app_id { get; set; }
        public string error_cat_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string log_level { get; set; }
        public int id { get; set; }
        public string error_message { get; set; }
        public string exception { get; set; }
    
        public virtual error_type error_type { get; set; }
        public virtual application application { get; set; }
    }
}
