//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.app_users = new HashSet<app_users>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string is_admin { get; set; }
        public string finstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string sign_up_date { get; set; }
        public string last_login { get; set; }
        public string active_inactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<app_users> app_users { get; set; }
        public string ReturnUrl { get; set; }
    }
}
